In [1]:
import pandas as pd

In [4]:
league_data = pd.read_csv('leagues.csv', index_col=0)

In [5]:
league_data

,Country,League_name,League_tier,Club_no,Players_no,Foreigners,Goals_per_match,Total_value
0,Albania,Kategoria Superiore,First Tier,10,268,131,2.020,48410000
1,Albania,Kategoria e Parë,Second Tier,12,299,109,2.250,14540000
2,Algeria,Ligue 1,First Tier,16,427,43,2.060,96900000
3,Andorra,Primera Divisió,First Tier,10,214,188,2.850,26170000
4,Andorra,Segona Divisió,Second Tier,8,246,99,4.920,1310000
...,...,...,...,...,...,...,...,...
182,Venezuela,Liga FUTVE Apertura,First Tier,14,406,80,2.335,82370000
183,Venezuela,Liga FUTVE 2,Second Tier,16,464,46,2.390,31560000
184,Vietnam,V.League 1,First Tier,14,440,85,2.670,57550000
185,Wales,Cymru Premier,First Tier,12,275,97,3.160,14180000
186,Wales,Cymru South,Second Tier,32,760,202,3.250,125000

In [7]:
league_data['Foreign_Player_Shaer'] = league_data['Foreigners'] / league_data['Players_no']
league_data['Players_per_club'] = league_data['Players_no'] / league_data['Club_no']
league_data['Value_per_club'] = league_data['Total_value'] / league_data['Club_no']

In [8]:
league_data

,Country,League_name,League_tier,Club_no,Players_no,Foreigners,Goals_per_match,Total_value,Foreign_Player_Shaer,Players_per_club,Value_per_club
0,Albania,Kategoria Superiore,First Tier,10,268,131,2.020,48410000,0.488806,26.800000,4.841000e+06
1,Albania,Kategoria e Parë,Second Tier,12,299,109,2.250,14540000,0.364548,24.916667,1.211667e+06
2,Algeria,Ligue 1,First Tier,16,427,43,2.060,96900000,0.100703,26.687500,6.056250e+06
3,Andorra,Primera Divisió,First Tier,10,214,188,2.850,26170000,0.878505,21.400000,2.617000e+06
4,Andorra,Segona Divisió,Second Tier,8,246,99,4.920,1310000,0.402439,30.750000,1.637500e+05
...,...,...,...,...,...,...,...,...,...,...,...
182,Venezuela,Liga FUTVE Apertura,First Tier,14,406,80,2.335,82370000,0.197044,29.000000,5.883571e+06
183,Venezuela,Liga FUTVE 2,Second Tier,16,464,46,2.390,31560000,0.099138,29.000000,1.972500e+06
184,Vietnam,V.League 1,First Tier,14,440,85,2.670,57550000,0.193182,31.428571,4.110714e+06
185,Wales,Cymru Premier,First Tier,12,275,97,3.160,14180000,0.352727,22.916667,1.181667e+06
186,Wales,Cymru South,Second Tier,32,760,202,3.250,125000,0.265789,23.750000,3.906250e+03

In [9]:
new_order = [
    "Country",
    "League_name",
    "League_tier",
    "Goals_per_match",
    "Foreign_Player_Shaer",
    "Players_per_club",
    "Value_per_club"
]

fixed_df = league_data[new_order]

fixed_df

,Country,League_name,League_tier,Goals_per_match,Foreign_Player_Shaer,Players_per_club,Value_per_club
0,Albania,Kategoria Superiore,First Tier,2.020,0.488806,26.800000,4.841000e+06
1,Albania,Kategoria e Parë,Second Tier,2.250,0.364548,24.916667,1.211667e+06
2,Algeria,Ligue 1,First Tier,2.060,0.100703,26.687500,6.056250e+06
3,Andorra,Primera Divisió,First Tier,2.850,0.878505,21.400000,2.617000e+06
4,Andorra,Segona Divisió,Second Tier,4.920,0.402439,30.750000,1.637500e+05
...,...,...,...,...,...,...,...
182,Venezuela,Liga FUTVE Apertura,First Tier,2.335,0.197044,29.000000,5.883571e+06
183,Venezuela,Liga FUTVE 2,Second Tier,2.390,0.099138,29.000000,1.972500e+06
184,Vietnam,V.League 1,First Tier,2.670,0.193182,31.428571,4.110714e+06
185,Wales,Cymru Premier,First Tier,3.160,0.352727,22.916667,1.181667e+06
186,Wales,Cymru South,Second Tier,3.250,0.265789,23.750000,3.906250e+03

In [10]:
fixed_df.to_csv('leagues_normalized.csv', index=True)